version: '3.8'

services:

  # service-user database
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smart-sales-net




  # Users microservice
  service-user:
    build:
      context: ./service-user
      dockerfile: Dockerfile
    container_name: service-user
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_db
      - SPRING_DATASOURCE_USERNAME=user_service
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - smart-sales-net


  # Authentication microservice
  service-auth:
    build:
      context: ./service-auth
      dockerfile: Dockerfile
    container_name: service-auth
    ports:
      - "8081:8081"
    environment:
      - SERVICE_USER_URL=http://service-user:8082
    depends_on:
      - service-user
    networks:
      - smart-sales-net


  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - AUTH_SERVICE_URL=http://service-auth:8081
      - USER_SERVICE_URL=http://service-user:8082
      - CUSTOMERS_SERVICE_URL=http://service-customers:8083
      - PRODUCTS_SERVICE_URL=http://service-products:8084
    depends_on:
      - service-auth
      - service-user
      - service-customers
      - service-products
    networks:
      - smart-sales-net


  # service-customers database
  customers-db:
    image: postgres:16-alpine
    container_name: customers-db
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: customers_service
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - customers_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U customers_service -d customers_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smart-sales-net


  # Customers microservice
  service-customers:
    build:
      context: ./service-customers
      dockerfile: Dockerfile
    container_name: service-customers
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customers-db:5432/customers_db
      - SPRING_DATASOURCE_USERNAME=customers_service
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      customers-db:
        condition: service_healthy
    networks:
      - smart-sales-net


    # database do service-products
  product-db:
    image: postgres:16-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: smart_sales_products
      POSTGRES_USER: user_products
      POSTGRES_PASSWORD: 123456
    ports:
      - "5434:5432" # Alterado para 5434 para evitar conflito na máquina host
    volumes:
      - product_db_data:/var/lib/postgresql/data # Apontado para o volume correto
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_products -d smart_sales_products" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smart-sales-net

    # microsserviço de produtos
  service-products:
    build:
      context: ./service-products
      dockerfile: Dockerfile
    container_name: service-products
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/smart_sales_products
      - SPRING_DATASOURCE_USERNAME=user_products
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      product-db:
        condition: service_healthy
    networks:
      - smart-sales-net

networks:
  smart-sales-net:
    driver: bridge

volumes:
  user_db_data:
  customers_db_data:
  product_db_data: